### ISSUE TITLE
Block Breakers/Placers get moved by frames facing towards them

### ISSUE THREAD

**Issue by MRebhan** [MrTJP/ProjectRed#1007]
The title basically says it all, block placers and block breakers that are facing towards a frame get moved by that frame too. This was not the case in the original RedPower 2, and this makes building frame quarrys much more difficult. Block Breakers and Block Placers should only be moved by a frame when facing away from that frame.

**Comment by MrTJP** [comment]
I had intentionally made it like this because it did not make a whole lot of sense why certain blocks would not stick to certain sides. So to keep everything consistent, this was the result. 

Since then I've been on the fence about what to do about it... I'll think about what to do about it some more...
