### ISSUE TITLE
[1.10.2] Crash when trying to place Block placer.

### ISSUE THREAD

**Issue by sybershot** [MrTJP/ProjectRed#1120]
Log: https://paste.ee/p/dSq0k
For some reason doesn't show up in JEI/NEI.

**Comment by Zedrimar** [comment]
If something doesn't show up in NEI or JEI, if you have BOTH installed then switch between the interface types (under JEI integration) and that sometimes reveals blocks that would otherwise not show.... This happened with mekanism's tanks as only the basic tank shows up in JEI's interface while the others will only show in NEI's interface mode

**Comment by MrTJP** [comment]
Fixed via 63e1853bc0d9f88b8606ed4ee1c5f821979a84d8
