### ISSUE TITLE
[1.10.2] Bad particles texture on breaking any machine

### ISSUE THREAD

**Issue by SirOutlander** [MrTJP/ProjectRed#1165]
Bad particles texture on breaking any machine

**Comment by MrTJP** [comment]
@covers1624 Is there a proper way to fix this yet?

**Comment by leagris** [comment]
@MrTJP While this issue is old and I am probably not experienced enough to fix this alone. I looked the ins and outs. I found an interesting related discussion in the Forge forums: http://www.minecraftforge.net/forum/topic/34305-18-block-break-particles-with-tesr/

As I read it, there are two ways of providing break particles when block is using a Tile Entity Special Renderer:
- Either a quick hack to provide a dummy model with a particle texture variable.
- Either implements CLIENT methods `addHitEffects` and `addDestroyEffects` as it is done here:  
  - https://github.com/Ordinastie/MalisisCore/blob/1.12/src/main/java/net/malisis/core/util/EntityUtils.java#L275-L365

    or by the ForgeMultipart project in Scala here: 
  - https://github.com/Chicken-Bones/ForgeMultipart/blob/master/src/codechicken/multipart/TIconHitEffects.scala#L13-L81

**Comment by MrTJP** [comment]
@covers1624 Can you confirm if this is still an issue on CCL's side?

**Comment by MrTJP** [comment]
This is no longer an issue on 1.15+
