### ISSUE TITLE
[1.7.10] Console says Projectred 4.8.1 available

### ISSUE THREAD

**Issue by m0nkm0nk** [MrTJP/ProjectRed#1221]
See title. Cant find :( 
I'm just a bit hopeful it somehow got updated 👍

**Comment by MrTJP** [comment]
1.7 is not being worked on at all and will not be updated. Must be some kind of bug.

**Comment by m0nkm0nk** [comment]
I expected this answer. No problem. Didnt play for 1 year so just imagine the hope I had when I saw that console message haha 💃  Thanks for the reply.

**Comment by thePalindrome** [comment]
Would it be possible to get this fixed though? (I'd imagine there's something on your side insisting that 4.8.1 exists, despite the oldest 1.10 version on CF being 4.8.4)

**Comment by Darkpye** [comment]
If we don't want the game client for an old 1.7.10 server to announce that ProjectRed 4.8.1 is available, since it really isn't available, how does one go about that. Is it there something that can be done our side? Does the Mod check some kind of online list? Surely this notice can be made to go away.
