### ISSUE TITLE
[1.12.2] [Suggection] Albedo integration

### ISSUE THREAD

**Issue by slava110** [MrTJP/ProjectRed#1285]
Albedo - something like Colored Lights Core but for 1.12.2. Maybe add integration to it?

**Comment by skellitor301** [comment]
I know 1.12 is likely not going to receive support as 1.16 is the current verison. But, considering 1.12 is still a very active version for minecraft modding, would there be any chance for support with Albedo or any other colored light mod for Project Red Illumination? The caged lights would be perfect to use for various alert signals inside bases and it would make the game much more immersive if they could emit their color rather than be a pure light source
