### ISSUE TITLE
Junction pipe bug?

### ISSUE THREAD

**Issue by Psy-Virus** [MrTJP/ProjectRed#1401]
Is the following intended behaviour, since 1.12.2?
Using the latest release 1.12.2-4.9.1.92

![2018-09-11_19 57 18](https://user-images.githubusercontent.com/6222200/45378546-109f5c00-b5fe-11e8-988d-cbbcf58e10e1.png)
![2018-09-11_19 57 24](https://user-images.githubusercontent.com/6222200/45378552-12691f80-b5fe-11e8-90be-41531742ea6a.png)
![2018-09-11_19 57 44](https://user-images.githubusercontent.com/6222200/45378566-1ac15a80-b5fe-11e8-8fd3-34105378b1f6.png)
![2018-09-11_19 57 59](https://user-images.githubusercontent.com/6222200/45378575-1f860e80-b5fe-11e8-9078-a41e4e6089f3.png)
![2018-09-11_20 03 50](https://user-images.githubusercontent.com/6222200/45378584-21e86880-b5fe-11e8-9195-034a018b73d1.png)

**Comment by Psy-Virus** [comment]
Could this be related to #1398 ?

**Comment by MrTJP** [comment]
I know what this bug is. In the config there is a number for "Routed Pipes: Max Detection Count". A single pipe is only able to search through a certain number of regular transport pipes before finding another router. Once it has finished, it will stop. 

Note that this is a limit on the total count. Therefore, if the limit is 100 and a router has connections on two sides, it will search 50 pipes in each direction. The more connections you add the less distance it is able to go to establish a connection to its neighbor. This is why in your pictures you can see that it can go left OR right, but when you connect both, it does not work. Add more routers along the path. 

This may also be related to #1398, but I'll look into it some more.

**Comment by Psy-Virus** [comment]
> Note that this is a limit on the total count. Therefore, if the limit is 100 and a router has connections on two sides, it will search 50 pipes in each direction.

That is interesting.
But it starts all over again from pipe to pipe, right?

So each pipe searches these 50 blocks in each dir?
