### ISSUE TITLE
(Bug) Item Crafting Extention chip not working at all

### ISSUE THREAD

**Issue by Greg9711** [MrTJP/ProjectRed#1416]
It says it in the title, the Item Crafting Extention chip doesn´t work and it always sends the items to the pipe where the Crafting chip is in instead of the pipe with the Extention chip in it. As long as i´m doing nothing wrong here you should only have to use the Extention chip and randomize the ID then put it into the Crafting chip (in the same slot as the Item that i want to be send elsewhere) and then put the Crafting chip at the output of the machine and the Extention chip at the input. I hope this issue will be resolved. Thanks for your time.

**Comment by Ommina** [comment]
I don't think you're doing it wrong, as I was brought here for the same reason.  The Interface Pipe is popping the item directly into the inventory to which it is attached, instead of sending the item to the location indicated by the Crafting Extension Chip.

I've also ensured that the Extension Chip is in the same location in the matrix, and that the UUID matches between the ghost copy in the Crafting Chip and the Extension Chip itself in the interface.

The whole of the pipe network is loaded (it is only a few blocks in size), and there are no breaks between the interface containing the Crafting Chip and the interface containing the Extension.

**Comment by Bartz24** [comment]
I have also be unable to get the crafting extension card to work as intended.
![craftingextension](https://user-images.githubusercontent.com/18143350/50941628-9f5ca200-1453-11e9-8538-85a608d1b238.png)

As you can see in the above picture, the Extension IDsare the same and the slots of the input and crafting extension match.  The input still ends up at the inventory connected to the interface pipe with the crafting chip, instead of the extension chip.

**Comment by JBYoshi** [comment]
I downloaded the Project Red code to take a look at this, and I think I found the cause. Creating a PR.

**Comment by PenguinOwl** [comment]
@JBYoshi assuming you have the builder set up, could you throw up a jar onto https://transfer.sh/ or something else?

**Comment by JBYoshi** [comment]
Sorry it took me so long to get around to this. Since Project Red made some extra changes that haven't been released yet, you'll also need to update the base mod. Note that this may introduce some other bugs with versions that I haven't fully tested for.

https://transfer.sh/qXJ7u/ProjectRed-1.12.2-4.9.2.jbyoshi1476-Base.jar
https://transfer.sh/Z1MJn/ProjectRed-1.12.2-4.9.2.jbyoshi1476-mechanical.jar
