### ISSUE TITLE
Game breaking bug - ICs get scrambled on game load (test case world for #1448 and #1245)

### ISSUE THREAD

**Issue by ccfb3ee765a58cae** [MrTJP/ProjectRed#1484]
See #1448 and #1245. ProjectRed has had this issue for a while, and 1b4e790fbf14322fbc825db521da34a1a4cf8baf did not fix it.

My hypothesis is that some of the *inputs* get stuck in random states whenever chunks are loaded.

For the same initial configuration, it seems that it's *almost* always the same inputs that get screwed up. It seems the output always ends up being something that is possible for the IC to output, which is why I believe it's the inputs that are getting stuck.

In this test case, I have a 4 to 16 decoder that, most of the time, gets its white input turned on, causing the output to be incremented by 1. In rare cases, the right input (toggle output) gets turned off. In order to fix it, you have to invert whatever input is getting stuck, or you can break and replace the IC. But the problem always comes back when the chunks reload.

[projectred-ic-scrambling-test-case.zip](https://github.com/MrTJP/ProjectRed/files/3239778/projectred-ic-scrambling-test-case.zip)

![Screenshot of test case world](https://i.imgur.com/MuAwWHl.png)

Mod versions:

```
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
ForgeMultipart-1.12.2-2.6.0.79-universal.jar
MrTJPCore-1.12.2-2.1.4.38-universal.jar
ProjectRed-1.12.2-4.9.2.110-Base.jar
ProjectRed-1.12.2-4.9.2.110-fabrication.jar
ProjectRed-1.12.2-4.9.2.110-integration.jar
ProjectRed-1.12.2-4.9.2.110-lighting.jar
ProjectRed-1.12.2-4.9.2.110-mechanical.jar
```

This is really frustrating because it makes nearly everything I had planned impossible or impractical.

**Comment by kremlar** [comment]
I did some testing related to this. It seems to be the case that if an IC loads and has a live (internal) wire going into an (internal) bundle cable, then it will scramble every wire that bundle is touching, including the original live wire. 

The live wire can come from an internal not gate(pic 1-3), or from an active external signal via input port(pics 4-7), and it can be an otherwise unused wire(pic 3), all reliably cause scrambling. 
A scrambled bundle does not affect independent wires(see pic 3). 
A bundle touching only a single color wire doesn't appear to scramble(see last two pics).


Stable
![1](https://user-images.githubusercontent.com/11057187/61180913-2c371280-a5d3-11e9-9696-15b1bbf4dfa1.png)
Unstable
![2](https://user-images.githubusercontent.com/11057187/61180916-2f320300-a5d3-11e9-9def-146ed292c85c.png)
Unstable
![2b](https://user-images.githubusercontent.com/11057187/61180917-322cf380-a5d3-11e9-9443-2ee5452389bf.png)
Stable
![3](https://user-images.githubusercontent.com/11057187/61180919-348f4d80-a5d3-11e9-8c8a-25717d8e76de.png)
Unstable with incoming signal.
![4](https://user-images.githubusercontent.com/11057187/61180920-36f1a780-a5d3-11e9-8a3b-5d92fc33c13c.png)
Stable
![5](https://user-images.githubusercontent.com/11057187/61181399-ec742900-a5da-11e9-8b33-774a66ed2867.png)
Unstable with incoming signals.
![6](https://user-images.githubusercontent.com/11057187/61181402-ee3dec80-a5da-11e9-9e29-c4d9324dff94.png)

Using version cclib 3.2.2.353, forge multipart cbe 2.6.1.81, tjpcore 2.1.4.43, project red core/fab/illum/trans 4.9.3.116

**Comment by MrTJP** [comment]
Thanks, that gives me a place to start looking.

**Comment by MrTJP** [comment]
Thanks for pointing me in the right place, @kremlar. I've found the source of this bug. Working on a fix.

**Comment by MrTJP** [comment]
I have a pull request for the fix but I need some testers to make sure nothing has regressed: #1505 

If you need help building the source, I can provide assistance.
