### ISSUE TITLE
Repeaters facing out of solid blocks don't update when those blocks are powered/unpowered until the repeater gets a block update

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MrTJP/ProjectRed#1485]
![2019-06-02_22 54 51](https://user-images.githubusercontent.com/18755309/58775222-1bce5980-858a-11e9-95ec-d4a0ece86809.png)

Flicking the lever does not change the output of the repeater until you give the repeater a block update. If a redstone signal is directly powering the repeater, it works fine.

The same setup replicated with vanilla repeaters works flawlessly.

**Comment by MrTJP** [comment]
Fixed with 4134ea2461a0ae30f4da4629f72ed66ac11ebe6a

For clarification, the bug was Project Red gates pulling weak signals of *neighbors* (which means it was using double-weak signals). As pictured above, that lever *should not* be effecting the gate at all, vanilla repeater or otherwise. That lever strongly powers the block below, so only blocks touching that strongly powered grass block should react. 

The stone block is only weakly powered in this case, which means the stone block itself *may* react to the signal if it would like, but neighbors of said stone block should not. ProjectRed gates were in fact, checking for weak signals to neighbors, instead of checking for strong signals to its neighbors. And because the lever does not send a block update all the way to the gate (which is neighbor of neighbor), the gate only reacts after a forced block update.

**Comment by embeddedt** [comment]
If anyone encounters this issue on 1.12, I have added a backported fix to the [Sledgehammer](https://www.curseforge.com/minecraft/mc-mods/sledgehammer) patch mod (versions 2.0.16 and newer). Please note that this is obviously not an official fix and wouldn't receive support from Project Red developers.
