### ISSUE TITLE
Screwdriver not "Sneak Rotating blocks in multiplayer" bug

### ISSUE THREAD

**Issue by Soviet-Steve** [MrTJP/ProjectRed#1561]
I am hosting and playing a minecraft server with project red installed, bandwidth and latency is not and issue, as I am hosting it on a local network.
In single player I can shift-rightclick a block (with any screwdriver) and it will spin, but I cannot do this in multiplayer.
Regular right clicking with a screw driver works.

**Comment by DreamlandSuperstar** [comment]
i'm currently experiencing the same problem

i'm running a local 1.12.2 minecraft server on forge with latest release of projectred available on curse/twitch

whenever i hold a screwdriver i can rotate any gate by right clicking on it but i'm unable to change its logic by sneak+right clicking.

This also only happens when i'm connected to my server and everything is fine in singleplayer

I have found nothing about this issue on the web nor inside the config files (maybe missed something?)

**Comment by MrTJP** [comment]
Behaves as expected on 1.18 multiplayer:
* Normal right click rotates gate
* Sneak right click goes through different gate modes

**Comment by DaytripperTX** [comment]
> Behaves as expected on 1.18 multiplayer:
> 
> * Normal right click rotates gate
> * Sneak right click goes through different gate modes

How can you close this issue because it works on 1.18.? This is still a bug on 1.12.2. It completely breaks core functionality for the mod on multiplayer. Please reopen and provide a solution.
