### ISSUE TITLE
Tick acceleration completely breaks machines

### ISSUE THREAD

**Issue by jmonsky** [MrTJP/ProjectRed#1602]
Using a ProjectE Watch of Flowing Time near a bluepower system breaks it. The batboxes switch between a broken texture and the normal texture, then everything connected to that bluepower network is permanently broken. They just drain power into nowhere and every block has to be replaced to fix it. Picking blocks back up and placing them they are still broken and need to be re-crafted.

I am unsure if other forms of tick acceleration breaks it as I don't know of any other ones in my pack, but I assume they have the same effect.

CCL Version: 3.2.3.358
Forge Version: 14.23.5.2847
MrTJPCore Version: 2.1.4.3
ProjectRed Version: 4.9.4.120

**Comment by MrTJP** [comment]
Been a while since I've looked at the Electrotine power system, but i'm fairly certain it works under the premise of all blocks in a network ticking together. Possibly it could still work if you accelerated an entire network, but doing a single block in the network can throw it off. 

Most tick accelerators I know of only increase the number of random ticks (used for plant growth, etc), not actual block ticks used for tile entity logic. Didn't even know that was a thing. I'll look into this but I have zero plans to support such behavior. Ticking tile entities out of sequence simply should not be done.

**Comment by Buh13246** [comment]
I can only confirm that in the Modpack Equivalent-Skies the autocrafting is broken when using watch of flowing time, because the Voltages on ProjectRed Low Load power lines go into infinity and are than replaced by question marks.

The Modpack uses ProjectRed Version: 4.9.1.92 and ProjectE: 1.12.2-PE1.4.0
