### ISSUE TITLE
[Question] Is there somewhere I can find a list of block ID's?

### ISSUE THREAD

**Issue by dsliX** [MrTJP/ProjectRed#1608]
Wasn't sure where to ask this and was looking for a while for this. I have a server for friends that uses a custom modpack with coloredlux, and I was looking to make a luxpack to make the lamps in this emit colored light. I know you can f3 and look at a block to see its ID but each color uses the same ID, so any help would be appreciated really.

**Comment by MrTJP** [comment]
Block IDs aren't really a thing anymore. If you're running an old enough version, then maybe they are configurable in the mod's config files. Otherwise, newer versions of minecraft handle block ID's internally. Also pretty sure all lamps in the past have used a single block ID, and their internal state controlled the colour.
