### ISSUE TITLE
Microblocks crash on placing illuminated button

### ISSUE THREAD

**Issue by Somebodyisnobody** [MrTJP/ProjectRed#1620]
**Describe the bug**
Nullpointer exception when placing button on microblocks

**To Reproduce**
1. Place illuminated button on multipart block

**Expected behavior**
Nothing like with the vanilla button.

**Crash Log**
[crash-2021-04-29_18.55.08-client.txt](https://github.com/MrTJP/ProjectRed/files/6400343/crash-2021-04-29_18.55.08-client.txt)

**Versions**
Checkout at bc91f0c89ff2ced2a1585504a57695106547c1fb

**Screenshots/Videos**

**Comment by MrTJP** [comment]
I think this may have been fixed on CBMultipart side. Using the latest commit from 1.15 branch and I can place the button on a Microblock cover just fine. What version of CBM are you running?

<img width="966" alt="Screen Shot 2021-04-29 at 9 58 25 PM" src="https://user-images.githubusercontent.com/1957405/116650480-0a3c8a80-a936-11eb-987b-dd2af7b5e0f3.png">

Btw, illumar buttons are not fully implemented yet. Still missing textures, etc.

**Comment by NDev8** [comment]
The client seems to crash when placing an illuminated button on a cover with solid block behind the cover. The screenshot shows all not crashing variants with green lamps. If someone tries to place the button on the cover behind the red lamp, the client is crashing. I think the button thinks it should be placed on the solid block, but it cannot because there is a cover before the solid block and thus crashing the client. Note that the second cover is not at the same position as the first cover.

![2021-04-30_18 42 05](https://user-images.githubusercontent.com/36798969/116726600-cc963b00-a9e3-11eb-8aa6-ee7a81175604.png)

**Comment by MrTJP** [comment]
Forgot to comment, but this seems to be fixed in 1.16 version of CB Multipart. Will know more later today once I'm finished porting.

**Comment by SharkBaitDLS** [comment]
Are Illumar Buttons still disabled in the 1.16 release? I see their recipe on the wiki but not in-game on Illumination 4.12.0.

**Comment by MrTJP** [comment]
Placement logic around multipart buttons has been re-written in CBMultipart (https://github.com/TheCBProject/CBMultipart/commit/ee4de5337c994f4b47b21c82e10ca60093366ede)

As for Illuminated buttons, they are not in atm. If/when they return, this issue won't apply anymore
