### ISSUE TITLE
Random game crash

### ISSUE THREAD

**Issue by Senliast** [MrTJP/ProjectRed#1623]
**Describe the bug**
The game randomly crashed and the error message told me to report this :) It happens randomly, cannot really tell what i am doing before it happens. But the last time i touched an OpenComputers monitor, this should trigger a door opening, the door is connected to PR wires. Then this happened. I re-entered the game, did exactly the same - everything works as it should, no crash.

**To Reproduce**
none

**Expected behavior**
The game doesnt crash.

**Crash Log**
The game crashed whilst exception in server tick loop
Error: java.lang.RuntimeException: Report this to ProjectRed developers
Код завершения: -1

https://pastebin.com/miAXK6yb

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 3.2.3.358
* FMP Version: 2.6.2.83
* MrTJPCore Version: 2.1.4.43
* ProjectRed Version: 4.9.4.120

**Screenshots/Videos**
none

**Comment by MrTJP** [comment]
This happens when block updates fire in an incorrect order or at incorrect times. Unfortunately I can't help unless you find some way to make it happen every time. There could be a million different things that could cause this, including other mods, CBMultipart, etc. If you find a way to reliably reproduce, place open the issue again.
