### ISSUE TITLE
[Suggestion] light updates

### ISSUE THREAD

**Issue by ElNico56** [MrTJP/ProjectRed#1687]
remove the light from gates, as the light updates lag the game a lot

**Comment by MrTJP** [comment]
This makes sense to me. I can make a config option for disabling gate light emission. Are you finding issues even though gates are not actually adjusting the light's on/off state or brightness?

**Comment by pat2rome** [comment]
I would actually really love this as a config option just for aesthetic reasons. If I make a cover over a gate to match my floor or the ground outside, it still looks obviously different because of the light leaking through it. If this could be disabled the cover would be indistinguishable from the blocks around it.

I'd love this even more if this config option was also added to 1.12!
