### ISSUE TITLE
1.18.2 Map corrupts when placing Generator-Cable-Battery-Cable-Frame Motor

### ISSUE THREAD

**Issue by al1-ce** [MrTJP/ProjectRed#1789]
**Describe the bug**
As title

**To Reproduce**
As title

**Expected behavior**
No crash

[**Crash Log**](https://pastebin.com/wgJPWS6i) (Expires in one month)

**Comment by MrTJP** [comment]
Can I have some screenshots and more details? I am unable to reproduce by placing these components in various configurations. Did you do anything besides just placing them? Did you insert dust into the generator? etc

<img width="966" alt="Screen Shot 2023-07-04 at 7 47 11 AM" src="https://github.com/MrTJP/ProjectRed/assets/1957405/c82f563b-e2a1-43a9-b25a-4fbd7c179402">

**Comment by al1-ce** [comment]
Sorry, can't do screenshots, almost immediately restored from backup and kinda afraid to replicate bug

And about perquisites, battery was already charged for some amount and generator had dust in it

**Comment by MrTJP** [comment]
Caused by a negative power storage value in your battery box. No idea what causes this issue. I've applied a temporary fix which will reset the battery box's power storage value to zero when this issue is detected to prevent the crash. Unfortunately since I can't reproduce this, I can't yet fix the actual issue causing the storage value to become negative in the first place.
