### ISSUE TITLE
[Bug] Fabricated Gates lose their NBT Data in 1.19.2

### ISSUE THREAD

**Issue by Ricci-dev** [MrTJP/ProjectRed#1834]
### Minecraft version

1.18.x

### CodeChickenLib version

4.3.2.490-universal

### CBMultipart version

3.2.0.139-universal

### ProjectRed version

4.17.0-beta+8

### What happened?

When placing fabricated gates, they are invisible and lose their NBT Data. At first they still work but when you break them in survival and replace them they don't work anymore and the gate lose all their information. If you copy them with mouse scroll wheel button then it says: <!> Corrupted NBT Data, please discard

### Crash log

[11:54:29] [Server thread/WARN]: Gate placement issue: no NBT on gate item

### How do you make it happen again?

Just try placing the gate from creative or any other produced IC with logic inside

**Comment by kitlith** [comment]
Also present in 1.18.2-4.17.0-beta-4, and when middle clicking to copy the block in creative. Rendering issue is probably separate from the NBT issue.

Root cause for the NBT issue is probably this: https://github.com/MrTJP/ProjectRed/blob/d046095956bdcdab82c093a135fe7c714d317daa/fabrication/src/main/java/mrtjp/projectred/fabrication/part/FabricatedGatePart.java#L88-L91

My reasoning is that using `/data get entity <username> Inventory[<slot>]` shows heaps of NBT for the original fabricated gate, almost nothing for the copied gate, and `/data get block <coords>` again shows heaps of NBT (which makes sense, because otherwise it wouldn't work in-world at all)
