### ISSUE TITLE
[Bug] Illumination Lights not Working with Stained Glass

### ISSUE THREAD

**Issue by ljtpetersen** [MrTJP/ProjectRed#1880]
### Minecraft version

1.19.x

### CodeChickenLib version

4.3.2

### CBMultipart version

3.2.0

### ProjectRed version

4.18.0

### What happened?

When looking at lit lamps from Project Red Illumination though stained or tinted glass, the lamps appear to be unlit. The two attached screenshots show the same lamps, one through regular glass, one through stained glass.

![2024-07-16_02 06 44](https://github.com/user-attachments/assets/2c210a24-2817-42b6-b9e0-23ceed1699a5)
![2024-07-16_02 06 50](https://github.com/user-attachments/assets/35cf39af-890d-4540-a425-229ad24da302)

### Crash log

The game did not crash.

### How do you make it happen again?

Place an lamp from Project Red Illumination, and power it such that it turns on. If the lamp is inverted, it does not need to be powered. Then, place a piece of stained or tinted glass, and observe the lamp through the glass.

**Comment by MrTJP** [comment]
This is a limitation of Minecraft's render engine. Many things cannot render through translucent materials, such as particle effects. Note that normal glass is transparent rather than translucent, so more things pass through it correctly.

If you enable the Fabulous rendering mode, it will use shader based transparency to fix quirks like this. Project Red lights were recently updated to work very well with this mode.
