### ISSUE TITLE
[Bug] Fixture, fallout, cages and lantern lights don't trigger lighting updates

### ISSUE THREAD

**Issue by Chachavo** [MrTJP/ProjectRed#1901]
### Minecraft version

1.19.x

### CodeChickenLib version

1.19.2-4.3.2.490

### CBMultipart version

1.19.2-3.2.0.139

### ProjectRed version

1.19.2-4.18.0

### What happened?

Tested with only Project red and starlight.
If a fixture light, fallout, cage or lantern light is turned on or off, it does not update the lighting so it will not affect anything

### Crash log

No crash

### How do you make it happen again?

Having starlight installed, place any inverted light that is not an illuminar lamp, then break it. The light remains.
Also placing down a normal non illuminar lamp, turning it on does not light up the surroundings
![2024-11-19_21 38 50](https://github.com/user-attachments/assets/77df84fa-f59a-4d97-85fb-f9fd3a50f2ca)
![2024-11-19_21 39 15](https://github.com/user-attachments/assets/97658e1c-abf3-4333-864f-e4672e6864e4)

**Comment by Chachavo** [comment]
I have just seen that it also occurs with any non full light block from cb multipart, perhaps it originates from there

**Comment by MrTJP** [comment]
Starlight makes very invasive changes to the MC lighting system, so you can't really expect everything to just work. CB Multipart is a special case that handles light levels slightly different from most blocks in vanilla. For example, there is no block state change when light level changes. 

Anyway, you can probably fix this by upgrading to MC 1.20+, but it won't be fixed in 1.19
