### ISSUE TITLE
Red Alloy Wires and MFR Rednet Cables Keep Each Other Switched On

### ISSUE THREAD

**Issue by richardcox13** [MrTJP/ProjectRed#299]
Recreate: set up a connection between red alloy wires and MineFactory Reloaded's Rednet cable. Switch it on and then remove the source (eg. place a redstone torch and then break it). Both the red alloy and rednet cables stay on.

A world restart (eg. disconnect/connect in SSP) clears the state.

It appears each is receiving the other's signal...

![2014-01-21_10 40 10a](https://f.cloud.github.com/assets/4578827/1962796/691c5a0c-828e-11e3-8dc7-234147b00233.png)

(I'm going to report this on Skyboy026's MFR Minecraft Forums topic as well.)

**Comment by Umaroth** [comment]
skyboy added an [interface](https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/api/rednet/connectivity/IRedstoneAlike.java) to the RedNet API that you would have to implement in order to fix this problem.

Also, there is good reason to pass a signal that way, I prefer RedNet cables to bundled cables since they don't require extra items to connect through a specific channel, also they don't have to be attached to a wall allowing more wire pathing options. There are tons of instances in which RedNet cables would be preferable to bundled cables if only they could interact with Red Alloy Wires properly.

**Comment by Jack-McKalling** [comment]
Has this still not been fixed yet? Currently it isn't possible to isolate different parallel signals from eachother if they pass through adjacent rednet cables, because you can't force adjacent cables to disconnect with multi-parts.

ProjectRed does allow this, but because of this update problem you can't connect those wires with rednet cables. So if you need rednet's logic, you are not able to layout the cables adjacent from eachother if signals need to be isolated.
