### ISSUE TITLE
Forge Multipart not found

### ISSUE THREAD

**Issue by frederikcreemers** [MrTJP/ProjectRed#623]
The installation instructions on the site make it very clear that Forge Multipart will be _AUTOMATICALLY INSTALLED_, however, when I start my MultiMC instance, I get the following message:

![screenshot 2014-11-17 13 50 35](https://cloud.githubusercontent.com/assets/737493/5070324/039235ac-6e66-11e4-8578-50093054ac82.png)

Is there a way to _MANUALLY_ install Forge Multipart?

**Minecraft version**: 1.7.10
**Forge Mod Loader version**: 10.13.2.1236

If you're interested in the contents of the log file mentioned in the error message, let me know.

**Comment by Rotfuchs-von-Vulpes** [comment]
i have the same problem on 1.7.10, i have Forge Multipart installed but it keeps saying there is no

**Comment by vizthex123** [comment]
> i have the same problem on 1.7.10, i have Forge Multipart installed but it keeps saying there is no

same here. Tried a few of the previous versions and it just won't detect multipart.

**Comment by CanD1802** [comment]
Have anyone found a way to solve this ?

**Comment by Ajern1** [comment]
Ich habe eine Lösung für mich gefunden,
Scheinbar wurde ForgeMultipart-1.7.10-1.2.0.345-universal.jar nicht korrekt runtergeladen und/oder Verschoben (Die Datei hatte kein richtigen Inhalt, aus irgendeinem Grund). 
Das Problem lies sich dann Beheben indem ich es nochmal manuell runtergeladen habe und direkt in den Ortner 1.7.10 verschoben/kopiert habe.
Ich hoffe das dass geholfen hat.

Google Translator:
I found a solution for myself.

Apparently, ForgeMultipart-1.7.10-1.2.0.345-universal.jar wasn't downloaded and/or moved correctly (the file didn't have the correct content, for some reason).

The problem was then fixed by manually downloading it again and moving/copying it directly into the 1.7.10 folder.

I hope that helps.
