### ISSUE TITLE
Bus Input Panel

### ISSUE THREAD

**Issue by kwstoudt** [MrTJP/ProjectRed#640]
Is it possible (or can it be made possible) to toggle an input on the panel and have it show as on/off on all panels connected to the same bundled cable network rather than having to go to the exact panel that it was turned on at in order to turn it off?

**Comment by evg-zhabotinsky** [comment]
[ProjectBlue](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2260994-project-blue-1-1-4-a-project-red-add-on) offers extremely nice control panels.

You can make it of any hollow cover and place 4x4 components on it (miniature versions of levers, buttons and fixtures, all in any of 16 colors) and add labels to them. You can also rotate it and mount it both on a wall and inside a wall. [Documentation](http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/ProjectBlue/doc/ControlPanel.html) explains everything that might be unclear.

In case of multiple control panels I'd suggest to use trigger latch, buttons to toggle its state and lamps to show current state.

About _"linked bus input panels"_: I'd say it's something really strange. I cannot imagine a real thing like that. A momentary version _with separate bus input for indicator lamps_ makes much more sense and is generally more useful IMO.

So my vision of _"momentary bus input panel"_ is as follows: You press one of the buttons, it sends redstone pulse to bundled output and releases itself _without lighting up at all_. At the same time you can manually light up any of the buttons using bundled input on the opposite size. It has to be a separate gate because it has bundled input instead of simple redstone input toggle-able version has.

**Comment by kwstoudt** [comment]
Don't advertise your mod on someone else's mod page -_-.

**Comment by evg-zhabotinsky** [comment]
It is not my mod. I just like it :) And the only real problem with it is multiplayer because it is new and one will hardly ever find it by accident so don't expect it on servers any soon.

BTW you _can_ connect to a server even if you have extra mods installed. (At least in this case, with plain forge server.)

**Comment by Sukasa** [comment]
I think the point is to have the functionality in *this* mod.

**Comment by evg-zhabotinsky** [comment]
Well, this mod (including planned RP-alike machines) makes much sense as a part of ProjectRed IMO. But it will take quite some time (and author's approval of course) to port and debug it.

So momentary input panel with separate input for indicators is the best bet for now. I'll take a look if I can do it myself.

**Comment by moTechPlz** [comment]
You can use the power level to differentiate between in and out. Power level 15 for the switch signal and 14 and lower for feedback light. Did something similar with the projred Illumar feedback button a while ago. https://vid.me/zTLm

**Comment by MrTJP** [comment]
Bus input panels will be staying the way they are.  If you need more complex functionality, go with something like computer craft touch screens.
