### ISSUE TITLE
[Feature Request] White-when-off lamps and multi-color lamps

### ISSUE THREAD

**Issue by makkarpov** [MrTJP/ProjectRed#721]
I want to suggest a new type of lamps that looks like a [LEDs with a transparent lens](https://cloud.githubusercontent.com/assets/1329592/6283303/9950b60e-b8f3-11e4-887a-87b0f7470944.png). These lamps are white when unpowered and shines with it's usual color when powered. Lamps of such type will be useful in building displays, signs and so on. Another type of lamps that I want to suggest - a lamps that accepts a bus and shines with a variable color based on a bus state (it can be simple one to one mapping from a wire to a color, or more complicated additive scheme).

**Comment by MrTJP** [comment]
White-when-off lamps seem too redundant. But as for the multicolored one, see #729.

**Comment by TheVoltrex** [comment]
@MrTJP , If I may, I would like to expand upon the "white-when-off" suggestion.. Instead of creating a new lamp type with that feature, perhaps there should be an incorporation across existing lamps? However, the feature I have in mind is a general regular and inverted lamp in one, with the player defining both the colors himself. For example: "Red when off, Green when on... White when off, blue when on..." Given on=redstone signal.. off=no redstone signal.
