### ISSUE TITLE
A cell like null cell for wires, but for bundles

### ISSUE THREAD

**Issue by makkarpov** [MrTJP/ProjectRed#843]
It would be very nice to have such cell, because in complex 64x64 IC designs it sometimes necessary to cross bundled wires over each other.  A cell that crosses bundle over plain wire will be also useful.

**Comment by cdogg111** [comment]
you can make this with fabrication now

**Comment by makkarpov** [comment]
AFAIK, currently fabrication does not have such cells. I can make "wire crossing IC", but I think that these cells will be most useful *inside* fabrication designs.

**Comment by makkarpov** [comment]
Tried to built 16-bit added/subtractor (IC has all sides bundled - one side for A input, one side for B input, one side for output and one side for carry and control wires) and quickly discovered that it almost impossible to feed all adding units with data unless some bundled crossing cell exists. So please implement it.

**Comment by MrTJP** [comment]
Yes, will do this soon.

**Comment by evg-zhabotinsky** [comment]
I wanted to give an idea for implementation of this feature, based on how wire nets work now now.

When IC is being compiled, tiles basically ask "What is placed left / right / below / on top of me?" and then connect nets accordingly. Checking what's to the right works like this pseudocode:
```
return tiles[x+1,y];
```

My idea is, a special "Wire crossover" tile can be added, which, whenever it is probed like that, redirects to the next tile in the same direction. That is, the previous pseudocode then will transform into following:
```
d=1;
while (isCrossover(tlies[x+d,y])) ++d;
return tiles[x+d,y];
```

Thus, these crossover tiles would "collapse" the grid, making it so that tiles on both ends of a "bridge" would behave as if they were adjacent.

The modification seems pretty straightforward, but I don't really know Scala and I'm mostly unfamiliar with this mod's internals, so I'm pretty much guaranteed to waste a lot of time on it and screw up a few times in process. So there won't be a pull request from me, at least for a while.

**Comment by MrTJP** [comment]
So this is actually what I’m currently working on at the moment, a way to have wires cross over on the same tile. At first my attempt was to simply make the cells into actual gates that passed signals from one side to another. Problem with that is self-powering feedback loops. So I decided to have the wirenet calculation consider such crossovers as you suggested. 

The trouble is that the entire wirenet calculation system was designed with the assumption that there is a single wire per tile. My solution to this is to have the wire tiles define a propagation mask depending on the input side. 

Basically, when wire nets are being created, they will ask the tile for directions to search in depending on the input side. This is opposed to assuming a wire can connect on all 4 sides regardless of which side the search came into the tile from. 

Creating special definitions for crossover tiles is also another solution but it will add complexity to the code. With my proposed solution, all wires can technically act as ‘crossovers’ as long as they define themselves as such so there won’t be any additional cases to consider. 

Anyway, my point is, I’m working on it. Should have something working soon. This is the last thing I want to finish before pushing a 1.11 build and then finishing up 1.12.

**Comment by evg-zhabotinsky** [comment]
Nice to know that it's being worked on.
I did notice the slightly inconvenient assumption of one net per tile, thus my suggestion to treat crossovers as "grid irregularities" (wormholes?) instead of actual wires or gates (thus without any nets at all), which should mostly require replacing calls to `ic.getTile(pos.offset(r))` with code that would skip over crossover tiles.
Using per-side nets and propagation masks is, of course, a more versatile solution. (And more difficult to implement.) It should also make it easier to implement array gates. Now that I think of it, making array gates work with my "wormhole" suggestion would be rather difficult.

**Comment by MrTJP** [comment]
This is being discussed here: #1616
