### ISSUE TITLE
Storage Drawers/Project Red compatibility issues.

### ISSUE THREAD

**Issue by MoxieGrrl** [MrTJP/ProjectRed#908]
Certain metals are not showing their nuggets in Storage Drawers' compacting drawers when Project Red is installed.

![2015-08-05_16 10 35](https://cloud.githubusercontent.com/assets/7219616/9098005/bf6d8008-3b8c-11e5-8fd0-a628af14d12d.png)

Copper, tin, and silver. I've been pulling my hair out for two days tracking this down. xD It also seems to be an ore dictionary issue as some mods' metals work and some do not.

![2015-08-05_16 21 06](https://cloud.githubusercontent.com/assets/7219616/9098341/dd117414-3b8e-11e5-9d36-0cc24a0eb85a.png)

The Tinkers copper (first on the bottom left) works, but the TE copper (third on the bottom left) does not. [Here's a link to a debug crash for modlist purposes.](http://pastebin.com/3CV8feuV)

**Comment by MrTJP** [comment]
Dont know how the mod is coded, but it might be because PR doesn't add any nuggets of its own.  Either way, this is certainly a problem on Storage Drawers' side.

**Comment by MoxieGrrl** [comment]
Removing Project Red Exploration solves the problem.

**Comment by MrTJP** [comment]
My ores are registered how they should be. I'm almost certain that this problem isn't on my end.

**Comment by lorddusk** [comment]
Have you heard of our lord and savior Ore-dictionary?

**Comment by MoxieGrrl** [comment]
I think that your mod just kind of exposed the problem, but we have no idea what's actually *causing* it. I'm going to open an issue at Storage Drawers as well. Regardless of whose code it is causing the issue, it definitely seems to be an interaction between these two mods. :/

**Comment by lorddusk** [comment]
Without ProjectRed : http://i.imgur.com/5pqB8x4.png
With ProjectRed : http://i.imgur.com/Ft0D5PJ.png

Both Forestry ( if the signs werent clear enough )

**Comment by jaquadro** [comment]
This happens when recipes can't be found in both directions (ingot -> block and block -> ingot, for example).  In the past this has been reliable, but in the last few months it's failing with a lot of different mod combinations.  I'm not sure if it's a change in Forge, the act of an individual mod unifying recipes, or just a shift in standard practices.

It's something I'll have to fix in on my end, and it means the Forge recipe lookup functions are no longer reliable for this purpose.
