### ISSUE TITLE
Strange interaction with between red alloy wires and microblocks

### ISSUE THREAD

**Issue by msgerbs** [MrTJP/ProjectRed#940]
I was working with redpower cables and XOR gates to power a Tinkers-Mechanics drawbridge. The XOR gate will receive a signal from a WR-CBE reciever on one side, and an adjacent lever on the other side. 
![2015-09-06_15 34 18](https://cloud.githubusercontent.com/assets/1313921/9706555/a4e1bcba-54ad-11e5-8021-c54cdb7995b9.png)

The red alloy wire from the lever runs directly adjacent to the drawbridge, but is NOT connecting because there's a microblock cover between them
![2015-09-06_15 29 42](https://cloud.githubusercontent.com/assets/1313921/9706556/b4196fd4-54ad-11e5-98d8-4acede9a11db.png)

But when the output of the XOR gate is triggered from that lever, the drawbridge block near the lever receives the redstone signal slightly sooner. As you can see is the second screenshot, however, it is NOT receiving a signal directly from that wire. When the XOR gate is triggered from the other side, it extends at the same time.
![2015-09-06_15 30 20](https://cloud.githubusercontent.com/assets/1313921/9706560/c3c17c4c-54ad-11e5-8103-d7680f2a5b17.png)

As far as I can tell, the only possibility remaining is some sort of bug whereby the drawbridge is somehow receiving a signal through the microblock ONLY when it is about to receive a signal from the directly connected wire. Please let me know if you need a video or more images, or if you think there may be another explanation.

**Comment by MrTJP** [comment]
Sorry but I can't seem to correctly understand the situation. Perhaps more images or a video?

**Comment by msgerbs** [comment]
Here's a video, hopefully it helps: https://youtu.be/7JTJ_OwiDyg

For the record, I'm on FTB Infinity which contains ProjectRed 4.6.1.80, but since I can't find anything else like this I can't imagine it's been fixed in a newer version.

**Comment by MrTJP** [comment]
Are the blocks under the drawbridges solid blocks?

**Comment by msgerbs** [comment]
Yes. Everything is solid blocks except the obvious covers.

**Comment by MrTJP** [comment]
Then the red alloy wires are strongly powering the blocks under the draw bridges, causing them to receive an indirect signal. If you don't want this to happen, replace the two red alloy wires under the draw bridges with insulated ones.

**Comment by msgerbs** [comment]
Which red alloy wires? The ones under the drawbridges are *supposed* to be powering the drawbridge. The only other wire that could be powering them is the one to the right, 2 blocks under the lever. The video clearly demonstrates that this wire is not powering the bridge at all.

**Comment by MrTJP** [comment]
Oh, okay, I was watching without audio..

If I'm correct, the bug you are referring to is that the drawbridges don't extend at the same time.  This may be happening because that wire you are placing to there right of the drawbridge (on the other side of the micro block) is still providing a block update to the drawbridge (as it should).  It might be worth forwarding this to the devs for TC.

So to recap, this is what I think is happening. 

1) Signal travels down the wire under the lever. The drawbridge receives a block update. It sees that there is no redstone applied. 

2) Signal travels up the other wire, alerts the drawbridges from the bottom. 

3) The drawbridge on the left sees the redstone signal, and starts extending right away.  However, the one on the right, since it has already checked for a signal, is waiting until the next tick to re-check.

Signals can only travel one wire at a time throughout the entire world. It may look like the top line and the bottom line of wires are updating at the same time, and although they do update during the same tick, it doesn't happen at the SAME time.

**Comment by msgerbs** [comment]
Ok, that makes sense. I will see if this happens with other blocks and determine if it's only happening with drawbridges or not, and report it to TC if it does.

**Comment by msgerbs** [comment]
Just tested this setup with vanilla redstone lamps and got the same result. Is this just an unavoidable quirk of the way block updates work?
