### ISSUE TITLE
Project:Red Expansion - Auto Crafting Bench bug

### ISSUE THREAD

**Issue by jordsta95** [MrTJP/ProjectRed#956]
Bug:
Auto Crafting Bench uses every item in a crafting recipe, even if it's reusable.

How to replicate:
Create a recipe in the project bench which uses an item which should not be consumed (but left in the crafting bench), save to Recipe Plan, use auto crafting bench.

How discovered (in case you are struggling to replicate):
Tried to create an auto-crafting setup for hamburgers from Pam's Harvestcraft which uses: toast, tofu, and a skillet (which should stay in the crafting table)

**Comment by bookerthegeek** [comment]
Interestingly enough redpower2 was coded this way on purpose with the saw to make the red silicone craft non (or at least expensive) to do.

Might be left over from that.

**Comment by MrTJP** [comment]
I thought I had intentionally made it so this was NOT the case. I will check again..

**Comment by MrTJP** [comment]
Fixed via 63fc6e95058e11d59a035209abd7ea161d252b0d

**Comment by trekkie22** [comment]
As far as I can see, it should be fixed with 4.7.0pre10. I just had the same problem with 4.7.0pre12 (.jar ends with 4.7.0pre12.95, latest files from curse, updated February 2016) so it seems that the fix does not work or is not included in pre12.

I expanded Life in the Woods with Project Red and tried to auto-craft stuffed eggplants from Pam's Harvestcraft. The Stuffed Eggplant is crafted, but the Bakeware, which should stay in the table, gets consumed.

**Comment by BloodyRain2k** [comment]
The auto crafting bench would be perfect for batch making horrible MC buckets into stacking Harvest Craft buckets, but given that the bench's eating up all items that would be left over after crafting (like cooking tools from Harvest Craft or an empty bucket in this case) is the bench sadly not useful for this at all :<

Atleast not for 1.7.10, maybe it was fixed in a later version, but sadly not in the one I'm using.

**Comment by MrTJP** [comment]
Pretty sure it's fixed in 1.10

**Comment by BloodyRain2k** [comment]
Doesn't really help me as I'm due to the mods I'm using stuck on 1.7.10, 
the usual MC problem :D

Good to know though for when somewhen things update, so like in 2 years 
maybe...
