### ISSUE TITLE
[request] Block Placer shouldn't move with frame

### ISSUE THREAD

**Issue by atsushiga** [MrTJP/ProjectRed#959]
As is the same with the original RP2, block placer shouldn't move when attached frame moves. With this function, we can make frame-place-and-move structure easily

**Comment by MrTJP** [comment]
This is by design. Its not intended to work exactly the same as RP2. There is a workaround, you just need to figure it out :)

**Comment by gcewing** [comment]
One way is to use another frame motor to move the block placer back into position, but that seems perversely complicated. Has anyone found a more elegant way?

**Comment by slayerain** [comment]
Man is right. I just hit the same problem. I used to do a very long elevators on redpower 2. When u build skyscraper from the lvl of the sea 63 block, up to max possible blocks position u need a long elevator. U can't use a stick go under the ground since it eventually will hit a bedrock. Redpower 2 solve this problem very easy. I thought project red was meant to continue redpower. I don't see a particular reason why block placer shouldn't be "immune" to a fram. At least from a block place side. Other side is ok, but wat the possible use of construction to put a block placer face to a frame that will drug it? Please do at least some sort of patch that will fix this issue. Would be very appreciated.

> 
> 
> One way is to use another frame motor to move the block placer back into position, but that seems perversely complicated. Has anyone found a more elegant way?

Thank, that's actually might be a temp solution.
